require:
  - rubocop-performance # gem 'rubocop-performance'
  - rubocop-rails       # gem 'rubocop-rails'

AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*  # sometimes we put something there
    - vendor/**/*
    - node_modules/**/*
    - db/schema.rb
    - db/structure.sql
    - config/application.rb
    - config/environments/*

Bundler/OrderedGems:
  Exclude:
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - config/routes.rb

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - test/support/build.rb

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/helpers/**/*
    - db/migrate/**/*
    - test/**/*
