default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %> # " for circle ci (not ')

development:
  <<: *default
  database: pingator_development

test:
  <<: *default
  database: pingator_test

production:
  <<: *default
  database: pingator_production
