default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %> # " for circle ci (not ')
  timeout: 5000

development:
  <<: *default
  database: db/pingator_development.sqlite3

test:
  <<: *default
  database: db/pingator_test.sqlite3

production:
  <<: *default
  database: db/pingator_production.sqlite3
